export const googleMapData = {
  countryCode: [
      "af",
      "al",
      "dz",
      "as",
      "ad",
      "ao",
      "ai",
      "ar",
      "am",
      "aw",
      "au",
      "at",
      "az",
      "bs",
      "bh",
      "bd",
      "bb",
      "by",
      "be",
      "bz",
      "bj",
      "bm",
      "bt",
      "bo",
      "ba",
      "bw",
      "br",
      "bn",
      "bg",
      "bf",
      "bi",
      "kh",
      "cm",
      "ca",
      "cv",
      "ky",
      "cf",
      "td",
      "cl",
      "cn",
      "co",
      "km",
      "cd",
      "cg",
      "cr",
      "ci",
      "hr",
      "cu",
      "cw",
      "cy",
      "cz",
      "dk",
      "dj",
      "dm",
      "do",
      "ec",
      "eg",
      "sv",
      "gq",
      "er",
      "ee",
      "et",
      "fo",
      "fj",
      "fi",
      "fr",
      "pf",
      "ga",
      "gm",
      "ge",
      "de",
      "gh",
      "gr",
      "gl",
      "gd",
      "gu",
      "gt",
      "gn",
      "gw",
      "gy",
      "ht",
      "hn",
      "hk",
      "hu",
      "is",
      "in",
      "id",
      "ir",
      "iq",
      "ie",
      "im",
      "il",
      "it",
      "jm",
      "jp",
      "jo",
      "kz",
      "ke",
      "ki",
      "kp",
      "kr",
      "kv",
      "kw",
      "kg",
      "la",
      "lv",
      "lb",
      "ls",
      "lr",
      "ly",
      "li",
      "lt",
      "lu",
      "mo",
      "mk",
      "mg",
      "mw",
      "my",
      "mv",
      "ml",
      "mt",
      "mh",
      "mr",
      "mu",
      "yt",
      "mx",
      "fm",
      "md",
      "mc",
      "mn",
      "me",
      "ma",
      "mz",
      "mm",
      "na",
      "np",
      "nl",
      "nc",
      "nz",
      "ni",
      "ne",
      "ng",
      "mp",
      "no",
      "om",
      "pk",
      "pw",
      "pa",
      "pg",
      "py",
      "pe",
      "ph",
      "pl",
      "pt",
      "pr",
      "qa",
      "ro",
      "ru",
      "rw",
      "ws",
      "sm",
      "st",
      "sa",
      "sn",
      "rs",
      "sc",
      "sl",
      "sg",
      "sk",
      "si",
      "sb",
      "so",
      "sx",
      "za",
      "ss",
      "es",
      "lk",
      "kn",
      "lc",
      "mf",
      "vc",
      "sd",
      "sr",
      "sz",
      "se",
      "ch",
      "sy",
      "tw",
      "tj",
      "tz",
      "th",
      "tl",
      "tg",
      "to",
      "tt",
      "tn",
      "tr",
      "tm",
      "tc",
      "tv",
      "ug",
      "ua",
      "ae",
      "gb",
      "us",
      "uy",
      "uz",
      "vu",
      "ve",
      "vn",
      "vi",
      "ps",
      "eh",
      "ye",
      "zm",
      "zw"
    ],
    countryName: [
      "Afghanistan",
      "Albania",
      "Algeria",
      "American Samoa",
      "Andorra",
      "Angola",
      "Antigua and Barbuda",
      "Argentina",
      "Armenia",
      "Aruba",
      "Australia",
      "Austria",
      "Azerbaijan",
      "Bahamas, The",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bermuda",
      "Bhutan",
      "Bolivia",
      "Bosnia and Herzegovina",
      "Botswana",
      "Brazil",
      "Brunei Darussalam",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Cape Verde",
      "Cayman Islands",
      "Central African Republic",
      "Chad",
      "Chile",
      "China",
      "Colombia",
      "Comoros",
      "Congo, Dem. Rep.",
      "Congo, Rep.",
      "Costa Rica",
      "Cote d'Ivoire",
      "Croatia",
      "Cuba",
      "Curacao",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Djibouti",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "Egypt, Arab Rep.",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Ethiopia",
      "Faeroe Islands",
      "Fiji",
      "Finland",
      "France",
      "French Polynesia",
      "Gabon",
      "Gambia, The",
      "Georgia",
      "Germany",
      "Ghana",
      "Greece",
      "Greenland",
      "Grenada",
      "Guam",
      "Guatemala",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Honduras",
      "Hong Kong SAR, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran, Islamic Rep.",
      "Iraq",
      "Ireland",
      "Isle of Man",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Korea, Dem. Rep.",
      "Korea, Rep.",
      "Kosovo",
      "Kuwait",
      "Kyrgyz Republic",
      "Lao PDR",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macao SAR, China",
      "Macedonia, FYR",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands",
      "Mauritania",
      "Mauritius",
      "Mayotte",
      "Mexico",
      "Micronesia, Fed. Sts.",
      "Moldova",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Morocco",
      "Mozambique",
      "Myanmar",
      "Namibia",
      "Nepal",
      "Netherlands",
      "New Caledonia",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Northern Mariana Islands",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Puerto Rico",
      "Qatar",
      "Romania",
      "Russian Federation",
      "Rwanda",
      "Samoa",
      "San Marino",
      "Sao Tome and Principe",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Slovak Republic",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "Somaliland",
      "South Africa",
      "South Sudan",
      "Spain",
      "Sri Lanka",
      "St. Kitts and Nevis",
      "St. Lucia",
      "St. Martin (French part)",
      "St. Vincent and the Grenadines",
      "Sudan",
      "Suriname",
      "Swaziland",
      "Sweden",
      "Switzerland",
      "Syrian Arab Republic",
      "Taiwan",
      "Tajikistan",
      "Tanzania",
      "Thailand",
      "Timor-Leste",
      "Togo",
      "Tonga",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Turks and Caicos Islands",
      "Tuvalu",
      "Uganda",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom",
      "United States",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Venezuela, RB",
      "Vietnam",
      "Virgin Islands (U.S.)",
      "West Bank and Gaza",
      "Western Sahara",
      "Yemen, Rep.",
      "Zambia",
      "Zimbabwe"
    ],
};

export const countryCodes = [
  'af',
  'al',
  'dz',
  'as',
  'ad',
  'ao',
  'ai',
  'ar',
  'am',
  'aw',
  'au',
  'at',
  'az',
  'bs',
  'bh',
  'bd',
  'bb',
  'by',
  'be',
  'bz',
  'bj',
  'bm',
  'bt',
  'bo',
  'ba',
  'bw',
  'br',
  'bn',
  'bg',
  'bf',
  'bi',
  'kh',
  'cm',
  'ca',
  'cv',
  'ky',
  'cf',
  'td',
  'cl',
  'cn',
  'co',
  'km',
  'cd',
  'cg',
  'cr',
  'ci',
  'hr',
  'cu',
  'cw',
  'cy',
  'cz',
  'dk',
  'dj',
  'dm',
  'do',
  'ec',
  'eg',
  'sv',
  'gq',
  'er',
  'ee',
  'et',
  'fo',
  'fj',
  'fi',
  'fr',
  'pf',
  'ga',
  'gm',
  'ge',
  'de',
  'gh',
  'gr',
  'gl',
  'gd',
  'gu',
  'gt',
  'gn',
  'gw',
  'gy',
  'ht',
  'hn',
  'hk',
  'hu',
  'is',
  'in',
  'id',
  'ir',
  'iq',
  'ie',
  'im',
  'il',
  'it',
  'jm',
  'jp',
  'jo',
  'kz',
  'ke',
  'ki',
  'kp',
  'kr',
  'kv',
  'kw',
  'kg',
  'la',
  'lv',
  'lb',
  'ls',
  'lr',
  'ly',
  'li',
  'lt',
  'lu',
  'mo',
  'mk',
  'mg',
  'mw',
  'my',
  'mv',
  'ml',
  'mt',
  'mh',
  'mr',
  'mu',
  'yt',
  'mx',
  'fm',
  'md',
  'mc',
  'mn',
  'me',
  'ma',
  'mz',
  'mm',
  'na',
  'np',
  'nl',
  'nc',
  'nz',
  'ni',
  'ne',
  'ng',
  'mp',
  'no',
  'om',
  'pk',
  'pw',
  'pa',
  'pg',
  'py',
  'pe',
  'ph',
  'pl',
  'pt',
  'pr',
  'qa',
  'ro',
  'ru',
  'rw',
  'ws',
  'sm',
  'st',
  'sa',
  'sn',
  'rs',
  'sc',
  'sl',
  'sg',
  'sk',
  'si',
  'sb',
  'so',
  'sx',
  'za',
  'ss',
  'es',
  'lk',
  'kn',
  'lc',
  'mf',
  'vc',
  'sd',
  'sr',
  'sz',
  'se',
  'ch',
  'sy',
  'tw',
  'tj',
  'tz',
  'th',
  'tl',
  'tg',
  'to',
  'tt',
  'tn',
  'tr',
  'tm',
  'tc',
  'tv',
  'ug',
  'ua',
  'ae',
  'gb',
  'us',
  'uy',
  'uz',
  'vu',
  've',
  'vn',
  'vi',
  'ps',
  'eh',
  'ye',
  'zm',
  'zw'
];
